// Copyright (c) 2025 Kirky.X
//
// Licensed under the MIT License
// See LICENSE file in the project root for full license information.

//! 基本向导示例
//!
//! 展示如何使用交互式向导来生成配置文件。
//!
//! ## 前提条件
//!
//! - 需要启用的特性：`derive`
//!
//! ## 运行方式
//!
//! ```bash
//! cargo run --bin 13-wizard-basic_wizard
//! ```

use confers::Config;
use serde::{Deserialize, Serialize};
use std::io::{self, Write};

// === Structs ===

#[derive(Debug, Clone, Serialize, Deserialize, Config)]
pub struct WizardConfig {
    pub app_name: String,
    pub version: String,
    pub environment: String,
    pub port: u16,
    pub debug: bool,
}

// === Main ===

fn main() -> anyhow::Result<()> {
    println!("=== 配置向导 ===\n");
    println!("欢迎使用 confers 配置向导！");
    println!("本向导将帮助您创建配置文件。\n");

    // 1. 收集配置信息
    let mut app_name = String::new();
    let mut version = String::new();
    let mut environment = String::new();
    let mut port = String::new();
    let mut debug = String::new();

    println!("请输入应用的名称 [my-app]: ");
    io::stdout().flush()?;
    io::stdin().read_line(&mut app_name)?;
    app_name = app_name.trim().to_string();
    if app_name.is_empty() {
        app_name = "my-app".to_string();
    }

    println!("请输入应用的版本号 [1.0.0]: ");
    io::stdout().flush()?;
    io::stdin().read_line(&mut version)?;
    version = version.trim().to_string();
    if version.is_empty() {
        version = "1.0.0".to_string();
    }

    println!("请输入运行环境 (development/production/staging) [development]: ");
    io::stdout().flush()?;
    io::stdin().read_line(&mut environment)?;
    environment = environment.trim().to_string();
    if environment.is_empty() {
        environment = "development".to_string();
    }

    println!("请输入应用监听的端口号 [8080]: ");
    io::stdout().flush()?;
    io::stdin().read_line(&mut port)?;
    port = port.trim().to_string();
    if port.is_empty() {
        port = "8080".to_string();
    }

    println!("是否启用调试模式 (true/false) [false]: ");
    io::stdout().flush()?;
    io::stdin().read_line(&mut debug)?;
    debug = debug.trim().to_string();
    if debug.is_empty() {
        debug = "false".to_string();
    }

    // 2. 构建配置
    let config = WizardConfig {
        app_name,
        version,
        environment,
        port: port.parse()?,
        debug: debug.parse()?,
    };

    // 3. 显示配置
    println!("\n=== 配置摘要 ===");
    println!("应用名称: {}", config.app_name);
    println!("版本号: {}", config.version);
    println!("环境: {}", config.environment);
    println!("端口号: {}", config.port);
    println!("调试模式: {}", config.debug);

    // 4. 生成配置文件
    println!("\n=== 生成配置文件 ===");
    let config_content = format!(
        r#"# {} Configuration
# Generated by confers wizard

app_name = "{}"
version = "{}"
environment = "{}"
port = {}
debug = {}
"#,
        config.app_name, config.app_name, config.version, config.environment, config.port, config.debug
    );

    let config_path = "src/13-wizard/configs/wizard.toml";
    std::fs::write(config_path, config_content)?;

    println!("✅ 配置文件已生成: {}", config_path);

    // 5. 询问是否保存
    print!("\n是否要保存此配置？(y/n): ");
    io::stdout().flush()?;

    let mut input = String::new();
    io::stdin().read_line(&mut input)?;

    if input.trim().to_lowercase() == "y" {
        println!("✅ 配置已保存");
    } else {
        println!("❌ 配置未保存");
        let _ = std::fs::remove_file(config_path);
    }

    println!("\n=== 向导完成 ===");
    println!("感谢使用 confers 配置向导！");

    Ok(())
}