// Copyright (c) 2026 Kirky.X🌠
// SPDX-License-Identifier: MIT

//! Flatten support: hoisting nested-struct keys into a flat key-space.
//!
//! The `#[config(flatten)]` field attribute promises that a nested struct's
//! fields are "promoted to the top level": configuration files may address
//! the nested fields directly at the root (alongside the dotted
//! `database.host` form supported natively by deserialization).
//!
//! This module provides the runtime helper the derive macro calls to
//! rewrite the merged JSON tree right before deserialization.

/// Static description of one flattened field, generated by the derive macro.
#[derive(Debug, Clone, Copy)]
pub struct FlattenSpec {
    /// Key of the nested field in the parent struct (serde field name).
    pub field_key: &'static str,
    /// Serde field names of the nested struct.
    pub nested_keys: &'static [&'static str],
}

/// Exposes a derived configuration struct's serde field names.
///
/// Implemented by every `#[derive(Config)]` struct; `#[config(flatten)]`
/// codegen reads the nested type's keys through this trait, so a flattened
/// field's type must also derive `Config` (or implement the trait by hand).
pub trait ConfigFieldKeys {
    /// Serde field names, in declaration order.
    const FIELD_KEYS: &'static [&'static str];
}

/// Hoist top-level keys addressed to flattened nested structs.
///
/// For every [`FlattenSpec`], a top-level key `k` where `k` is one of the
/// nested struct's field names is moved under `field_key.k`, unless:
/// - `k` is one of the parent's own field names (explicit parent fields win,
///   mirroring `#[serde(flatten)]`), or
/// - the key already exists inside the nested object (explicit nested value
///   wins over the hoisted top-level one).
///
/// When the nested object does not exist yet but any hoistable key is
/// present, it is created. A pre-existing **non-object** value at
/// `field_key` (e.g. `"database": null`) is replaced by the hoisted object
/// when hoistable keys exist: the top-level keys are the configuration the
/// user actually wrote, and the displaced scalar could not deserialize into
/// the nested struct anyway.
pub fn hoist_flattened(json: &mut serde_json::Value, own_keys: &[&str], specs: &[FlattenSpec]) {
    let Some(obj) = json.as_object_mut() else {
        return;
    };

    for spec in specs {
        // Keys already present inside the nested object keep their nested
        // value, so their top-level counterpart must stay put.
        let nested_contains = |k: &str| {
            obj.get(spec.field_key)
                .and_then(|v| v.as_object())
                .is_some_and(|n| n.contains_key(k))
        };
        let hoistable: Vec<&str> = spec
            .nested_keys
            .iter()
            .copied()
            .filter(|k| !own_keys.contains(k) && obj.contains_key(*k) && !nested_contains(k))
            .collect();
        if hoistable.is_empty() {
            continue;
        }

        // Move the hoistable values out of the top level first (avoids
        // aliasing `obj` while the nested object is borrowed mutably).
        let mut moved = serde_json::Map::new();
        for k in hoistable {
            if let Some(v) = obj.remove(k) {
                moved.insert(k.to_string(), v);
            }
        }

        // Seed (or extend) the nested object.
        match obj.get_mut(spec.field_key) {
            Some(serde_json::Value::Object(nested)) => {
                for (k, v) in moved {
                    nested.insert(k, v);
                }
            }
            _ => {
                obj.insert(spec.field_key.to_string(), serde_json::Value::Object(moved));
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn hoists_top_level_keys_into_missing_nested_object() {
        let mut json = json!({"host": "db", "port": 5432, "app_name": "x"});
        hoist_flattened(
            &mut json,
            &["app_name"],
            &[FlattenSpec {
                field_key: "database",
                nested_keys: &["host", "port"],
            }],
        );
        assert_eq!(json["database"]["host"], json!("db"));
        assert_eq!(json["database"]["port"], 5432);
        assert_eq!(json["app_name"], json!("x"));
        assert!(json.get("host").is_none(), "hoisted key must be moved");
    }

    #[test]
    fn explicit_parent_field_wins_over_nested_key() {
        let mut json = json!({"host": "top", "port": 1});
        hoist_flattened(
            &mut json,
            &["host"],
            &[FlattenSpec {
                field_key: "database",
                nested_keys: &["host", "port"],
            }],
        );
        assert_eq!(
            json["host"],
            json!("top"),
            "parent's own field is untouched"
        );
        assert_eq!(json["database"]["port"], 1);
        assert!(json["database"].get("host").is_none());
    }

    #[test]
    fn explicit_nested_value_wins_over_hoisted_top_level_key() {
        let mut json = json!({"host": "flat", "database": {"host": "nested"}});
        hoist_flattened(
            &mut json,
            &[],
            &[FlattenSpec {
                field_key: "database",
                nested_keys: &["host"],
            }],
        );
        assert_eq!(json["database"]["host"], json!("nested"));
        assert_eq!(json["host"], json!("flat"), "conflicting top key stays put");
    }

    #[test]
    fn non_object_root_is_a_noop() {
        let mut json = json!([1, 2, 3]);
        hoist_flattened(
            &mut json,
            &[],
            &[FlattenSpec {
                field_key: "database",
                nested_keys: &["host"],
            }],
        );
        assert_eq!(json, json!([1, 2, 3]));
    }
}
